###
POST http://127.0.0.1:8282/api/customer/fake-customer-id/orders
Content-Type: application/json

{
  "CustomerID": "fake-customer-id",
  "Items": [
    {"ID": "3", "Quantity": 3 }
  ]
}

###
GET http://127.0.0.1:8282/api/customer/fake-customer-id/order/1749144852
