###
POST http://127.0.0.1:8282/api/customer/fake-customer-id/orders
Content-Type: application/json

{
  "CustomerID": "fake-customer-id",
  "Items": [
    {"ID": "item-1", "Quantity": 3 },
    {"ID": "item-2", "Quantity": 1 },
    {"ID": "item-3", "Quantity": 8 }
  ]
}

###
GET http://127.0.0.1:8282/api/customer/fake-customer-id/order/1749144852
