fallback-grpc-addr: 127.0.0.1:3030

dial-grpc-timeout: 10

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

consul:
  addr: 127.0.0.1:8500

order:
  service-name: order
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002
  metrics-addr: 127.0.0.1:9123

stock:
  service-name: stock
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003
  metrics-addr: 127.0.0.1:9124

payment:
  service-name: payment
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004
  metrics-addr: 127.0.0.1:9125

kitchen:
  service-name: kitchen

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "order"

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool-size: 10
    max-conn: 100
    conn-timeout: 1000
    read-timeout: 1000
    write-timeout: 100

mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3307
  db-name: "gorder"

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"
